// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Server.Data;
using Server.Models.Items;
using System;

namespace Server.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180508143223_AddItemModels")]
    partial class AddItemModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Heroes.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Attack");

                    b.Property<int>("BlueprintId");

                    b.Property<int>("Defence");

                    b.Property<int>("Dodge");

                    b.Property<int>("Health");

                    b.Property<int>("Magic");

                    b.Property<int>("MagicPower");

                    b.Property<int>("MagicResistance");

                    b.Property<int>("MaxDamage");

                    b.Property<int>("MinDamage");

                    b.Property<int>("PersonalAttack");

                    b.Property<int>("PersonalDefense");

                    b.Property<int?>("RegionId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("Hero");
                });

            modelBuilder.Entity("Server.Models.Heroes.HeroBlueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Attack");

                    b.Property<int>("Defense");

                    b.Property<string>("Description");

                    b.Property<int>("Dodge");

                    b.Property<int>("Health");

                    b.Property<int>("HeroClassId");

                    b.Property<int>("Magic");

                    b.Property<int>("MagicPower");

                    b.Property<int>("MagicResistance");

                    b.Property<int>("MaxDamage");

                    b.Property<int>("MinDamage");

                    b.Property<string>("Name");

                    b.Property<int>("PersonalAttack");

                    b.Property<int>("PersonalDefense");

                    b.Property<string>("PortraitImgUrl");

                    b.HasKey("Id");

                    b.HasIndex("HeroClassId");

                    b.ToTable("HeroBlueprints");
                });

            modelBuilder.Entity("Server.Models.Heroes.HeroBlueprintClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttackGainChance");

                    b.Property<int>("DefenseGainChance");

                    b.Property<string>("Description");

                    b.Property<int>("MagicGainChance");

                    b.Property<int>("MagicPowerGainChance");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("HeroBlueprintClass");
                });

            modelBuilder.Entity("Server.Models.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlueprintId");

                    b.Property<int>("HeroId");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("HeroId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Server.Models.Items.ItemBlueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("ItemSlotType");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ItemBlueprints");
                });

            modelBuilder.Entity("Server.Models.Users.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime?>("DateRead");

                    b.Property<bool>("IsRead");

                    b.Property<DateTime>("MessageSent");

                    b.Property<bool>("RecipientDeleted");

                    b.Property<int>("RecipientId");

                    b.Property<bool>("SenderDeleted");

                    b.Property<int>("SenderId");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Server.Models.Users.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description");

                    b.Property<bool>("IsMain");

                    b.Property<string>("PublicId");

                    b.Property<string>("Url");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Server.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Gender");

                    b.Property<string>("Interests");

                    b.Property<DateTime>("LastActive");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSald");

                    b.Property<string>("Username");

                    b.Property<int?>("WorldId");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Models.Worlds.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<int?>("WorldId");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Server.Models.Worlds.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("Server.Models.Heroes.Hero", b =>
                {
                    b.HasOne("Server.Models.Heroes.HeroBlueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.Worlds.Region")
                        .WithMany("Heroes")
                        .HasForeignKey("RegionId");

                    b.HasOne("Server.Models.Users.User")
                        .WithMany("Heroes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Server.Models.Heroes.HeroBlueprint", b =>
                {
                    b.HasOne("Server.Models.Heroes.HeroBlueprintClass", "HeroClass")
                        .WithMany()
                        .HasForeignKey("HeroClassId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Models.Items.Item", b =>
                {
                    b.HasOne("Server.Models.Items.ItemBlueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Server.Models.Heroes.Hero", "Hero")
                        .WithMany("Items")
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Models.Users.Message", b =>
                {
                    b.HasOne("Server.Models.Users.User", "Recipient")
                        .WithMany("MessagesRecieved")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Models.Users.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Server.Models.Users.Photo", b =>
                {
                    b.HasOne("Server.Models.Users.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Server.Models.Users.User", b =>
                {
                    b.HasOne("Server.Models.Worlds.World")
                        .WithMany("Players")
                        .HasForeignKey("WorldId");
                });

            modelBuilder.Entity("Server.Models.Worlds.Region", b =>
                {
                    b.HasOne("Server.Models.Worlds.World")
                        .WithMany("Regions")
                        .HasForeignKey("WorldId");
                });
#pragma warning restore 612, 618
        }
    }
}
